package com.osleigh.url_shortener.service;

import com.osleigh.url_shortener.config.properties.DomainProperties;
import com.osleigh.url_shortener.domain.UrlEntity;
import com.osleigh.url_shortener.dto.UrlShortenRequest;
import com.osleigh.url_shortener.dto.UrlShortenResponse;
import com.osleigh.url_shortener.exception.ShortCodeGenerationException;
import com.osleigh.url_shortener.service.strategy.collision.CollisionResolver;
import com.osleigh.url_shortener.service.strategy.generator.ShortCodeGenerator;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

// 동시 충돌 대응 재시도 조율 담당
// Writer가 단일 원자 단위라면, Orchestrator는 그 시도들을 조율
@Service
@RequiredArgsConstructor
public class UrlShortenerService {

    private static final int MAX_ATTEMPTS = 5;

    private final DomainProperties domainProperties;
    private final ShortCodeGenerator codeGenerator;
    private final CollisionResolver collisionResolver;
    private final UrlWriter urlWriter;

    @Transactional
    public UrlShortenResponse shorten(UrlShortenRequest request) {
        if (request.isCustomRequest()) {
            return shortenWithCustomAlias(request);
        }
        return shortenWithAutoGeneratedCode(request);
    }

    private UrlShortenResponse shortenWithCustomAlias(UrlShortenRequest request) {
        try {
            String shortCode = request.getAlias();
            UrlEntity urlEntity = request.toEntity(shortCode);
            urlWriter.write(urlEntity);
            return UrlShortenResponse.fromEntity(urlEntity, domainProperties.getHost());
        } catch (DataIntegrityViolationException e) {
            if (!isShortCodeConstraintViolation(e)) throw e;
            throw new IllegalStateException("이미 사용 중인 alias입니다: " + request.getAlias(), e);
        }
    }

    private UrlShortenResponse shortenWithAutoGeneratedCode(UrlShortenRequest request) {
        String shortCode = codeGenerator.generate(request.getOriginalURL());
        int attempts = 0;
        do {
            try {
                UrlEntity urlEntity = request.toEntity(shortCode);
                urlWriter.write(urlEntity);
                return UrlShortenResponse.fromEntity(urlEntity, domainProperties.getHost());
            } catch (DataIntegrityViolationException e) {
                if (!isShortCodeConstraintViolation(e)) throw e;
                if (++attempts >= MAX_ATTEMPTS) {
                    throw new ShortCodeGenerationException(
                        "단축 코드 생성 실패: 최대 시도 횟수(" + MAX_ATTEMPTS + ") 초과");
                }
                shortCode = collisionResolver.resolve(shortCode);
            }
        } while (true);
    }

    private boolean isShortCodeConstraintViolation(DataIntegrityViolationException e) {
        String msg = e.getMostSpecificCause().getMessage();
        return msg != null && msg.toLowerCase().contains("short_code");
    }
}
